import mysql from 'mysql2/promise';

interface SchemeData {
  slug: string; name: string; name_hi: string; category: string;
  level: string; ministry: string; description: string;
  benefit_summary: string; benefit_amount_max: number | null;
  apply_url: string | null; official_url: string | null;
  min_age: number | null; max_age: number | null;
  gender: 'all' | 'male' | 'female' | 'transgender';
  states: string; categories: string; max_income: number | null;
  occupations: string; education_min: string | null;
  area: 'all' | 'urban' | 'rural'; bpl_required: boolean;
  minority_only: boolean; disability_only: boolean;
  how_to_apply: string; documents_required: string;
  meta_title: string; meta_description: string;
  source_url: string;
}

const SCHEMES: SchemeData[] = [
  {
    slug: 'pm-awas-yojana', name: 'Pradhan Mantri Awas Yojana (PMAY)', name_hi: 'प्रधानमंत्री आवास योजना',
    category: 'housing', level: 'central', ministry: 'Ministry of Housing and Urban Affairs',
    description: 'PMAY aims to provide affordable housing to the urban and rural poor. Under PMAY-Urban, beneficiaries get interest subsidy on home loans. Under PMAY-Gramin, beneficiaries get financial assistance to build houses in rural areas. The scheme targets to provide pucca houses with basic amenities like toilet, electricity, water, and LPG connection to all eligible families.',
    benefit_summary: 'Interest subsidy of up to Rs 2.67 lakh on home loans for urban beneficiaries. Rs 1.20 lakh to Rs 1.30 lakh grant for rural house construction.',
    benefit_amount_max: 267000, apply_url: 'https://pmaymis.gov.in', official_url: 'https://pmay-urban.gov.in',
    min_age: 21, max_age: null, gender: 'all', states: '["all"]', categories: '["all"]',
    max_income: 1800000, occupations: '["all"]', education_min: null, area: 'all',
    bpl_required: false, minority_only: false, disability_only: false,
    how_to_apply: '1. Visit pmaymis.gov.in or your nearest Common Service Centre (CSC).\n2. Click on "Citizen Assessment" and select your category (EWS, LIG, MIG-I, MIG-II).\n3. Enter Aadhaar number and fill the application form.\n4. Submit required documents.\n5. Application will be verified by the Urban Local Body.\n6. For PMAY-Gramin, apply through your Gram Panchayat or Block office.',
    documents_required: '["Aadhaar card","Income certificate","Bank account details","Property documents (if applicable)","Caste certificate (for SC/ST)","Affidavit of not owning a pucca house"]',
    meta_title: 'PM Awas Yojana - Eligibility, Subsidy, Apply Online', meta_description: 'Apply for PM Awas Yojana. Get up to Rs 2.67 lakh subsidy on home loans. Check eligibility and documents required.',
    source_url: 'https://pmay-urban.gov.in'
  },
  {
    slug: 'ayushman-bharat', name: 'Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana (AB-PMJAY)', name_hi: 'आयुष्मान भारत - प्रधानमंत्री जन आरोग्य योजना',
    category: 'healthcare', level: 'central', ministry: 'Ministry of Health and Family Welfare',
    description: 'Ayushman Bharat is the world\'s largest government-funded health insurance scheme. It provides cashless and paperless health coverage of up to Rs 5 lakh per family per year for secondary and tertiary care hospitalization. Over 12 crore poor and vulnerable families (approximately 55 crore beneficiaries) are covered. Treatment is available at over 28,000 empanelled hospitals across India.',
    benefit_summary: 'Free health insurance cover of Rs 5 lakh per family per year for hospitalization at empanelled hospitals across India.',
    benefit_amount_max: 500000, apply_url: 'https://beneficiary.nha.gov.in', official_url: 'https://pmjay.gov.in',
    min_age: null, max_age: null, gender: 'all', states: '["all"]', categories: '["all"]',
    max_income: 300000, occupations: '["all"]', education_min: null, area: 'all',
    bpl_required: false, minority_only: false, disability_only: false,
    how_to_apply: '1. Check eligibility at mera.pmjay.gov.in by entering your mobile number or ration card number.\n2. If eligible, visit nearest Ayushman Bharat Arogya Mitra at an empanelled hospital.\n3. Carry your Aadhaar card and ration card.\n4. Get your e-card generated on the spot.\n5. Use the e-card for cashless treatment at any empanelled hospital.',
    documents_required: '["Aadhaar card","Ration card","Mobile number","SECC data (auto-verified)"]',
    meta_title: 'Ayushman Bharat PMJAY - Free Health Cover Rs 5 Lakh', meta_description: 'Get free health insurance of Rs 5 lakh per family under Ayushman Bharat PMJAY. Check eligibility and apply.',
    source_url: 'https://pmjay.gov.in'
  },
  {
    slug: 'pm-kisan', name: 'PM Kisan Samman Nidhi Yojana', name_hi: 'प्रधानमंत्री किसान सम्मान निधि योजना',
    category: 'agriculture', level: 'central', ministry: 'Ministry of Agriculture and Farmers Welfare',
    description: 'PM-KISAN provides income support of Rs 6,000 per year to all landholding farmer families across the country. The amount is paid in three equal installments of Rs 2,000 each, directly transferred to the bank account of the farmer. Over 11 crore farmers benefit from this scheme. It was launched on 24 February 2019.',
    benefit_summary: 'Rs 6,000 per year (Rs 2,000 every 4 months) directly transferred to farmer bank accounts.',
    benefit_amount_max: 6000, apply_url: 'https://pmkisan.gov.in', official_url: 'https://pmkisan.gov.in',
    min_age: 18, max_age: null, gender: 'all', states: '["all"]', categories: '["all"]',
    max_income: null, occupations: '["farmer"]', education_min: null, area: 'all',
    bpl_required: false, minority_only: false, disability_only: false,
    how_to_apply: '1. Visit pmkisan.gov.in and click on "New Farmer Registration".\n2. Select your state and enter Aadhaar number.\n3. Fill the registration form with personal and land details.\n4. Alternatively, visit your nearest CSC or local revenue office.\n5. Verification will be done by state government.\n6. Once approved, Rs 2,000 will be credited every 4 months.',
    documents_required: '["Aadhaar card","Bank account passbook","Land ownership documents (khatauni/khasra)","Mobile number"]',
    meta_title: 'PM Kisan Yojana - Rs 6000 Per Year for Farmers', meta_description: 'Get Rs 6,000 per year under PM Kisan scheme. Check eligibility, installment status, and apply online.',
    source_url: 'https://pmkisan.gov.in'
  },
  {
    slug: 'mudra-loan', name: 'Pradhan Mantri MUDRA Yojana', name_hi: 'प्रधानमंत्री मुद्रा योजना',
    category: 'business', level: 'central', ministry: 'Ministry of Finance',
    description: 'MUDRA (Micro Units Development and Refinance Agency) provides loans up to Rs 10 lakh to non-corporate, non-farm small and micro enterprises. Loans are available under three categories: Shishu (up to Rs 50,000), Kishore (Rs 50,001 to Rs 5 lakh), and Tarun (Rs 5,00,001 to Rs 10 lakh). No collateral is required. Available through banks, NBFCs, and MFIs.',
    benefit_summary: 'Business loans up to Rs 10 lakh without collateral. Three categories: Shishu, Kishore, and Tarun.',
    benefit_amount_max: 1000000, apply_url: 'https://www.mudra.org.in', official_url: 'https://www.mudra.org.in',
    min_age: 18, max_age: null, gender: 'all', states: '["all"]', categories: '["all"]',
    max_income: null, occupations: '["self_employed","business"]', education_min: null, area: 'all',
    bpl_required: false, minority_only: false, disability_only: false,
    how_to_apply: '1. Prepare a business plan or project report.\n2. Visit any bank, NBFC, or MFI that offers MUDRA loans.\n3. Fill the MUDRA loan application form.\n4. Submit identity, address, and business documents.\n5. Bank will process and approve the loan.\n6. No collateral needed for loans up to Rs 10 lakh.',
    documents_required: '["Aadhaar card","PAN card","Business plan or project report","Bank statements (6 months)","Proof of business existence","Passport size photos"]',
    meta_title: 'MUDRA Loan - Up to Rs 10 Lakh Without Collateral', meta_description: 'Apply for MUDRA loan up to Rs 10 lakh without collateral. Shishu, Kishore, Tarun categories. Check eligibility.',
    source_url: 'https://www.mudra.org.in'
  },
  {
    slug: 'sukanya-samriddhi', name: 'Sukanya Samriddhi Yojana', name_hi: 'सुकन्या समृद्धि योजना',
    category: 'women', level: 'central', ministry: 'Ministry of Finance',
    description: 'Sukanya Samriddhi Yojana is a savings scheme for the girl child. Parents can open an account in the name of a girl child below 10 years of age. The scheme offers an attractive interest rate of 8.2% per annum (as of 2026). Minimum deposit is Rs 250 per year and maximum is Rs 1.5 lakh. The account matures after 21 years. Deposits qualify for tax deduction under Section 80C. Interest earned and maturity amount are also tax-free.',
    benefit_summary: '8.2% interest rate savings account for girl child. Tax-free under Section 80C. Matures at age 21.',
    benefit_amount_max: 150000, apply_url: null, official_url: 'https://www.nsiindia.gov.in',
    min_age: 0, max_age: 10, gender: 'female', states: '["all"]', categories: '["all"]',
    max_income: null, occupations: '["all"]', education_min: null, area: 'all',
    bpl_required: false, minority_only: false, disability_only: false,
    how_to_apply: '1. Visit any post office or authorized bank (SBI, PNB, etc.).\n2. Fill the Sukanya Samriddhi account opening form.\n3. Submit girl child\'s birth certificate and parent\'s ID proof.\n4. Deposit minimum Rs 250 to open the account.\n5. Continue depositing for 15 years.\n6. Account matures when girl turns 21.',
    documents_required: '["Girl child birth certificate","Parent Aadhaar card","Parent PAN card","Address proof","Passport size photos"]',
    meta_title: 'Sukanya Samriddhi Yojana - 8.2% Interest for Girls', meta_description: 'Open Sukanya Samriddhi account for your daughter. 8.2% interest, tax-free returns, matures at 21.',
    source_url: 'https://www.nsiindia.gov.in'
  },
];

// Additional 95 schemes defined in compact format
const MORE_SCHEMES: SchemeData[] = [
  { slug: 'atal-pension', name: 'Atal Pension Yojana', name_hi: 'अटल पेंशन योजना', category: 'pension', level: 'central', ministry: 'Ministry of Finance', description: 'Atal Pension Yojana provides guaranteed minimum pension of Rs 1,000 to Rs 5,000 per month after age 60. Available to all citizens aged 18-40 years with a bank account. The government co-contributes 50% of the subscriber contribution for 5 years for eligible subscribers who joined before 31 December 2015. Pension amount depends on the age of joining and contribution amount.', benefit_summary: 'Guaranteed pension of Rs 1,000 to Rs 5,000 per month after age 60. Government co-contributes for eligible subscribers.', benefit_amount_max: 60000, apply_url: null, official_url: 'https://www.npscra.nsdl.co.in/scheme-details.php', min_age: 18, max_age: 40, gender: 'all', states: '["all"]', categories: '["all"]', max_income: null, occupations: '["all"]', education_min: null, area: 'all', bpl_required: false, minority_only: false, disability_only: false, how_to_apply: '1. Visit your bank branch where you have a savings account.\n2. Fill the APY registration form.\n3. Choose pension amount (Rs 1,000 to Rs 5,000).\n4. Bank will auto-debit monthly contribution.', documents_required: '["Aadhaar card","Bank account","Mobile number"]', meta_title: 'Atal Pension Yojana - Pension Rs 5000/Month After 60', meta_description: 'Get guaranteed pension under Atal Pension Yojana. Rs 1,000 to Rs 5,000 per month after age 60.', source_url: 'https://www.npscra.nsdl.co.in' },
  { slug: 'pmegp', name: 'PM Employment Generation Programme (PMEGP)', name_hi: 'प्रधानमंत्री रोजगार सृजन कार्यक्रम', category: 'business', level: 'central', ministry: 'Ministry of MSME', description: 'PMEGP provides financial assistance for setting up new micro-enterprises in manufacturing and service sectors. Maximum project cost is Rs 50 lakh for manufacturing and Rs 20 lakh for service sector. Government subsidy ranges from 15% to 35% of the project cost depending on the category and area.', benefit_summary: 'Subsidy of 15% to 35% on project cost for new businesses. Up to Rs 50 lakh for manufacturing units.', benefit_amount_max: 1750000, apply_url: 'https://www.kviconline.gov.in/pmegpeportal/pmegphome/index.jsp', official_url: 'https://msme.gov.in', min_age: 18, max_age: null, gender: 'all', states: '["all"]', categories: '["all"]', max_income: null, occupations: '["self_employed","business","unemployed"]', education_min: '8th', area: 'all', bpl_required: false, minority_only: false, disability_only: false, how_to_apply: '1. Apply online at kviconline.gov.in/pmegpeportal.\n2. Select project type and fill application form.\n3. Submit project report and documents.\n4. Application reviewed by District Task Force Committee.\n5. Bank sanctions loan after approval.', documents_required: '["Aadhaar card","PAN card","Project report","Educational certificates","Caste certificate (if applicable)","EDP training certificate"]', meta_title: 'PMEGP Scheme - 35% Subsidy for New Business', meta_description: 'Start your business with PMEGP scheme. Get 15% to 35% subsidy on project cost. Apply online.', source_url: 'https://msme.gov.in' },
  { slug: 'pm-vishwakarma', name: 'PM Vishwakarma Yojana', name_hi: 'पीएम विश्वकर्मा योजना', category: 'skill-training', level: 'central', ministry: 'Ministry of MSME', description: 'PM Vishwakarma provides support to traditional artisans and craftspeople working with their hands and tools. Covers 18 trades including carpenters, blacksmiths, goldsmiths, potters, tailors, and cobblers. Benefits include skill training, toolkit, credit support up to Rs 3 lakh at 5% interest, and digital payment incentive.', benefit_summary: 'Skill training, free toolkit, and loans up to Rs 3 lakh at 5% interest for artisans and craftspeople.', benefit_amount_max: 300000, apply_url: 'https://pmvishwakarma.gov.in', official_url: 'https://pmvishwakarma.gov.in', min_age: 18, max_age: null, gender: 'all', states: '["all"]', categories: '["all"]', max_income: null, occupations: '["self_employed"]', education_min: null, area: 'all', bpl_required: false, minority_only: false, disability_only: false, how_to_apply: '1. Register at pmvishwakarma.gov.in with Aadhaar and mobile.\n2. Verification by Gram Panchayat/ULB.\n3. Enroll for skill training (5-15 days).\n4. Receive toolkit after training.\n5. Apply for credit support from bank.', documents_required: '["Aadhaar card","Bank account","Mobile number","Trade-related proof"]', meta_title: 'PM Vishwakarma - Loans for Artisans & Craftspeople', meta_description: 'Get skill training, toolkit, and Rs 3 lakh loan at 5% under PM Vishwakarma. For artisans and craftspeople.', source_url: 'https://pmvishwakarma.gov.in' },
  { slug: 'pm-kaushal-vikas', name: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY)', name_hi: 'प्रधानमंत्री कौशल विकास योजना', category: 'skill-training', level: 'central', ministry: 'Ministry of Skill Development', description: 'PMKVY is India\'s largest skill certification scheme. It provides free short-term training (150-300 hours) and certification for youth in various industry-relevant courses. Trainees also receive Rs 8,000 stipend and placement assistance. Over 1.4 crore youth have been trained under this scheme.', benefit_summary: 'Free skill training, Rs 8,000 stipend, certification, and placement assistance for youth.', benefit_amount_max: 8000, apply_url: 'https://www.pmkvyofficial.org', official_url: 'https://www.pmkvyofficial.org', min_age: 15, max_age: 45, gender: 'all', states: '["all"]', categories: '["all"]', max_income: null, occupations: '["unemployed","student"]', education_min: null, area: 'all', bpl_required: false, minority_only: false, disability_only: false, how_to_apply: '1. Visit pmkvyofficial.org and find training centres near you.\n2. Choose a course from available options.\n3. Enroll at the training centre with Aadhaar.\n4. Complete training and pass assessment.\n5. Receive government-recognized certificate.', documents_required: '["Aadhaar card","Bank account","Mobile number","Educational certificates"]', meta_title: 'PMKVY - Free Skill Training with Stipend', meta_description: 'Get free skill training and Rs 8,000 stipend under PMKVY. Placement assistance included.', source_url: 'https://www.pmkvyofficial.org' },
  { slug: 'stand-up-india', name: 'Stand Up India Scheme', name_hi: 'स्टैंड अप इंडिया योजना', category: 'business', level: 'central', ministry: 'Ministry of Finance', description: 'Stand Up India facilitates bank loans between Rs 10 lakh and Rs 1 crore for SC/ST and women entrepreneurs to set up greenfield enterprises. Each bank branch must provide at least one loan to a SC/ST borrower and one to a woman borrower. Loans are available for manufacturing, services, or trading sector.', benefit_summary: 'Bank loans from Rs 10 lakh to Rs 1 crore for SC/ST and women entrepreneurs. No collateral up to Rs 10 lakh.', benefit_amount_max: 10000000, apply_url: 'https://www.standupmitra.in', official_url: 'https://www.standupmitra.in', min_age: 18, max_age: null, gender: 'all', states: '["all"]', categories: '["sc","st"]', max_income: null, occupations: '["self_employed","business"]', education_min: null, area: 'all', bpl_required: false, minority_only: false, disability_only: false, how_to_apply: '1. Visit standupmitra.in and register.\n2. Submit loan application online.\n3. Or visit the nearest bank branch.\n4. Submit business plan and documents.\n5. Bank processes loan within 15 days.', documents_required: '["Aadhaar card","PAN card","Caste certificate (SC/ST)","Business plan","Address proof","Bank statements"]', meta_title: 'Stand Up India - Loans for SC/ST & Women Entrepreneurs', meta_description: 'Get business loans Rs 10 lakh to Rs 1 crore under Stand Up India for SC/ST and women entrepreneurs.', source_url: 'https://www.standupmitra.in' },
];

// Remaining 90 schemes in compact INSERT format
const BATCH_SCHEMES: Array<[string,string,string,string,string,string,string,string,number|null,string|null,string|null,number|null,number|null,string,string,string,number|null,string,string|null,string,boolean,boolean,boolean,string,string]> = [
  ['startup-india','Startup India Scheme','स्टार्टअप इंडिया','business','central','DPIIT','Provides tax exemption, easy compliance, funding support, and mentoring for DIPP-recognized startups. Startups get 3-year income tax exemption, self-certification for 6 labour laws, and access to Fund of Funds.','Tax exemption, funding, mentoring for DIPP-recognized startups. 3-year income tax holiday.',null,'https://www.startupindia.gov.in','https://www.startupindia.gov.in',null,null,'all','["all"]','["all"]',null,'["business","self_employed"]',null,'all',false,false,false,'Register at startupindia.gov.in. Get DIPP recognition. Apply for benefits.','["Aadhaar","PAN","Certificate of Incorporation","Business plan"]'],
  ['pm-svanidhi','PM SVANidhi - Street Vendor Loan','पीएम स्वनिधि','business','central','Ministry of Housing','Provides working capital loan of Rs 10,000 (1st tranche), Rs 20,000 (2nd), Rs 50,000 (3rd) to street vendors. 7% interest subsidy. Digital payment rewards.','Collateral-free loans up to Rs 50,000 for street vendors with interest subsidy.',50000,'https://pmsvanidhi.mohua.gov.in','https://pmsvanidhi.mohua.gov.in',18,null,'all','["all"]','["all"]',null,'["self_employed","daily_wage"]',null,'urban',false,false,false,'Apply at pmsvanidhi.mohua.gov.in or nearest bank/ULB.','["Aadhaar","Vending certificate/Letter of Recommendation","Bank account"]'],
  ['nps-national-pension','National Pension System (NPS)','राष्ट्रीय पेंशन प्रणाली','pension','central','Ministry of Finance','Market-linked pension scheme for all citizens. Government employees get 14% employer contribution. Additional tax benefit of Rs 50,000 under Section 80CCD(1B). Flexible investment choices.','Market-linked pension with tax benefits. Rs 50,000 extra deduction under 80CCD(1B).',50000,null,'https://www.npscra.nsdl.co.in',18,70,'all','["all"]','["all"]',null,'["all"]',null,'all',false,false,false,'Open NPS account at any Point of Presence (PoP) - banks, post offices. Or online at enps.nsdl.com.','["Aadhaar","PAN","Bank account","Photo"]'],
  ['pmsby-suraksha-bima','PM Suraksha Bima Yojana (PMSBY)','प्रधानमंत्री सुरक्षा बीमा योजना','insurance','central','Ministry of Finance','Accidental death and disability insurance at Rs 20 per year. Coverage: Rs 2 lakh for accidental death, Rs 2 lakh for total permanent disability, Rs 1 lakh for partial permanent disability.','Accident insurance of Rs 2 lakh at just Rs 20 per year.',200000,null,'https://www.jansuraksha.gov.in',18,70,'all','["all"]','["all"]',null,'["all"]',null,'all',false,false,false,'Enroll through your bank. Auto-debit of Rs 20 per year from savings account.','["Aadhaar","Bank account"]'],
  ['pmjjby-jeevan-jyoti','PM Jeevan Jyoti Bima Yojana (PMJJBY)','प्रधानमंत्री जीवन ज्योति बीमा योजना','insurance','central','Ministry of Finance','Life insurance cover of Rs 2 lakh at Rs 436 per year. Covers death due to any reason. Renewable every year. Available through banks and post offices.','Life insurance of Rs 2 lakh at Rs 436 per year premium.',200000,null,'https://www.jansuraksha.gov.in',18,50,'all','["all"]','["all"]',null,'["all"]',null,'all',false,false,false,'Enroll through your bank branch or net banking. Auto-debit from savings account.','["Aadhaar","Bank account","Nominee details"]'],
  ['pm-ujjwala','PM Ujjwala Yojana','प्रधानमंत्री उज्ज्वला योजना','social','central','Ministry of Petroleum','Free LPG connection to women from BPL families. Includes free gas stove and first refill. Covers security deposit for cylinder and regulator. Over 10 crore connections provided since 2016.','Free LPG connection with stove and first refill for BPL women.',1600,null,'https://www.pmuy.gov.in',18,null,'female','["all"]','["all"]',null,'["all"]',null,'all',true,false,false,'Apply at nearest LPG distributor with BPL documents and Aadhaar.','["Aadhaar card","BPL ration card","Bank account","Photo"]'],
  ['jan-dhan-yojana','PM Jan Dhan Yojana','प्रधानमंत्री जन धन योजना','finance','central','Ministry of Finance','Zero-balance bank account with RuPay debit card, Rs 2 lakh accident insurance, and Rs 30,000 life cover. Overdraft facility of Rs 10,000 for eligible accounts. Over 52 crore accounts opened.','Free bank account with RuPay card, Rs 2 lakh accident insurance, Rs 10,000 overdraft.',200000,null,'https://pmjdy.gov.in',10,null,'all','["all"]','["all"]',null,'["all"]',null,'all',false,false,false,'Visit any bank branch with Aadhaar card. No minimum balance required.','["Aadhaar card","Photo"]'],
  ['digital-india-scheme','Digital India Programme','डिजिटल इंडिया कार्यक्रम','skill-training','central','MeitY','Umbrella programme for digital infrastructure, digital literacy, and digital services delivery. Includes PMGDISHA for digital literacy training to 6 crore rural households.','Free digital literacy training. Wi-Fi hotspots. Digital services in rural areas.',null,null,'https://digitalindia.gov.in',14,null,'all','["all"]','["all"]',null,'["all"]',null,'rural',false,false,false,'Enroll for PMGDISHA at nearest training centre or CSC.','["Aadhaar card"]'],
  ['pm-fasal-bima','PM Fasal Bima Yojana','प्रधानमंत्री फसल बीमा योजना','agriculture','central','Ministry of Agriculture','Crop insurance at 2% premium for Kharif, 1.5% for Rabi crops. Government subsidizes remaining premium. Covers crop loss from natural calamities, pests, and diseases.','Crop insurance at 1.5-2% premium. Government pays remaining. Covers natural calamities.',null,'https://pmfby.gov.in','https://pmfby.gov.in',null,null,'all','["all"]','["all"]',null,'["farmer"]',null,'rural',false,false,false,'Apply through bank at time of taking crop loan or through CSC/insurance company.','["Aadhaar","Land records","Bank account","Sowing certificate"]'],
  ['soil-health-card','Soil Health Card Scheme','मृदा स्वास्थ्य कार्ड योजना','agriculture','central','Ministry of Agriculture','Free soil testing and health card for all farmers. Card provides crop-wise recommendations for nutrients and fertilizers. Helps farmers improve crop productivity and reduce fertilizer costs.','Free soil testing with crop-wise fertilizer recommendations for all farmers.',null,null,'https://soilhealth.dac.gov.in',null,null,'all','["all"]','["all"]',null,'["farmer"]',null,'rural',false,false,false,'Visit nearest agriculture office or Krishi Vigyan Kendra for soil sample collection.','["Aadhaar","Land details"]'],
  ['kisan-credit-card','Kisan Credit Card (KCC)','किसान क्रेडिट कार्ड','agriculture','central','Ministry of Agriculture','Easy credit for farmers at 4% interest (with subsidy). Covers crop production, post-harvest, and allied activities. Limit up to Rs 3 lakh. Also available for fishermen and animal husbandry farmers.','Agricultural credit at 4% interest for crop production and allied activities.',300000,null,'https://pmkisan.gov.in',18,null,'all','["all"]','["all"]',null,'["farmer"]',null,'all',false,false,false,'Apply at nearest bank branch with land documents.','["Aadhaar","Land documents","Photo","Bank account"]'],
  ['national-scholarship-portal','National Scholarship Portal Schemes','राष्ट्रीय छात्रवृत्ति पोर्टल','education','central','Ministry of Education','Umbrella portal for 20+ central scholarship schemes including post-matric SC/ST scholarships, minority scholarships, merit-cum-means scholarships, and more.','Multiple scholarships from Rs 1,000 to Rs 2 lakh per year for students from various backgrounds.',200000,'https://scholarships.gov.in','https://scholarships.gov.in',null,null,'all','["all"]','["sc","st","obc","ews"]',800000,'["student"]','10th','all',false,false,false,'Apply at scholarships.gov.in. Fresh applications open July-November each year.','["Aadhaar","Income certificate","Caste certificate","Bank account","Previous marksheet","Institution verification"]'],
  ['ddugky','Deen Dayal Upadhyaya Grameen Kaushalya Yojana','दीन दयाल उपाध्याय ग्रामीण कौशल्य योजना','skill-training','central','Ministry of Rural Development','Skill training and placement for rural poor youth aged 15-35. Free residential training for 3-12 months with guaranteed placement at minimum Rs 6,000/month salary.','Free skill training with guaranteed job placement at minimum Rs 6,000/month for rural youth.',null,'https://ddugky.gov.in','https://ddugky.gov.in',15,35,'all','["all"]','["all"]',null,'["unemployed","student"]',null,'rural',true,false,false,'Contact nearest Project Implementing Agency (PIA) or Block office.','["Aadhaar","BPL card","Educational certificates","Bank account"]'],
  ['nrega-mgnrega','MGNREGA - Mahatma Gandhi National Rural Employment Guarantee Act','मनरेगा','employment','central','Ministry of Rural Development','Guarantees 100 days of wage employment per year to every rural household. Current wage rate is Rs 267-374 per day depending on state. Unemployment allowance if work not provided within 15 days.','100 days guaranteed employment per year at Rs 267-374 per day for rural households.',37400,null,'https://nrega.nic.in',18,null,'all','["all"]','["all"]',null,'["unemployed","daily_wage","farmer"]',null,'rural',false,false,false,'Apply to Gram Panchayat for job card. Request work in writing. Work must be provided within 15 days.','["Aadhaar","Photo","Bank account"]'],
  ['pmay-gramin','PM Awas Yojana - Gramin','प्रधानमंत्री आवास योजना - ग्रामीण','housing','central','Ministry of Rural Development','Financial assistance of Rs 1.20 lakh (plain areas) to Rs 1.30 lakh (hilly/difficult areas) for construction of pucca houses in rural areas. Includes MGNREGA convergence for 90/95 person-days of unskilled labour.','Rs 1.20 lakh to Rs 1.30 lakh for rural house construction with MGNREGA labour support.',130000,null,'https://pmayg.nic.in',18,null,'all','["all"]','["all"]',null,'["all"]',null,'rural',true,false,false,'Identified through SECC-2011 data. Apply through Gram Panchayat/Block office if not in list.','["Aadhaar","SECC data","Bank account","Photo"]'],
  ['mid-day-meal','PM POSHAN (Mid-Day Meal) Scheme','प्रधानमंत्री पोषण शक्ति निर्माण','education','central','Ministry of Education','Free cooked meal for all children in government and aided schools from Class 1 to Class 8. Covers over 11.8 crore children. Provides balanced nutrition to improve learning outcomes.','Free nutritious lunch for all government school children from Class 1 to 8.',null,null,'https://pmposhan.education.gov.in',6,14,'all','["all"]','["all"]',null,'["student"]',null,'all',false,false,false,'Automatic for children enrolled in government and government-aided schools.','[]'],
  ['beti-bachao-beti-padhao','Beti Bachao Beti Padhao','बेटी बचाओ बेटी पढ़ाओ','women','central','Ministry of WCD','Addresses declining child sex ratio and promotes education of the girl child. Includes awareness campaigns, multi-sectoral action in 405 districts, and convergence with other schemes for girl child welfare.','Awareness and support for girl child education and survival. Multi-sectoral action in 405 districts.',null,null,'https://wcd.nic.in',0,18,'female','["all"]','["all"]',null,'["all"]',null,'all',false,false,false,'Benefits through convergence with other schemes. Awareness campaigns run at district level.','[]'],
  ['pm-matru-vandana','PM Matru Vandana Yojana (PMMVY)','प्रधानमंत्री मातृ वंदना योजना','women','central','Ministry of WCD','Cash incentive of Rs 5,000 for first live birth and Rs 6,000 for second (if girl child). Paid in installments for pregnancy registration, ante-natal check-up, and child birth registration.','Rs 5,000-6,000 cash incentive for pregnant women for institutional delivery.',6000,'https://pmmvy.wcd.gov.in','https://pmmvy.wcd.gov.in',19,null,'female','["all"]','["all"]',null,'["all"]',null,'all',false,false,false,'Register at Anganwadi centre or health facility. Submit MCP card and bank details.','["Aadhaar","MCP card","Bank account","Pregnancy registration proof"]'],
  ['swachh-bharat-gramin','Swachh Bharat Mission - Gramin','स्वच्छ भारत मिशन - ग्रामीण','social','central','Ministry of Jal Shakti','Rs 12,000 incentive for construction of individual household latrine (IHHL) in rural areas. Also supports community sanitary complexes and solid/liquid waste management.','Rs 12,000 for toilet construction in rural households.',12000,null,'https://swachhbharatmission.gov.in',null,null,'all','["all"]','["all"]',null,'["all"]',null,'rural',false,false,false,'Apply through Gram Panchayat or Block Development Office.','["Aadhaar","Photo of house without toilet","Bank account"]'],
  ['jal-jeevan-mission','Jal Jeevan Mission','जल जीवन मिशन','social','central','Ministry of Jal Shakti','Aims to provide tap water connection to every rural household by 2024. Functional Household Tap Connection (FHTC) providing 55 liters per capita per day. Over 14 crore connections provided.','Free tap water connection for every rural household. 55 litres per person per day.',null,null,'https://jaljeevanmission.gov.in',null,null,'all','["all"]','["all"]',null,'["all"]',null,'rural',false,false,false,'Implemented through Gram Panchayats. Contact village water committee or Block office.','[]'],
  ['national-rural-livelihood','Deendayal Antyodaya Yojana - NRLM','दीनदयाल अंत्योदय योजना - एनआरएलएम','business','central','Ministry of Rural Development','Promotes self-employment through Self Help Groups (SHGs). Provides revolving fund of Rs 10,000-15,000 per SHG, community investment fund, and bank linkage for credit.','SHG formation support, revolving fund, and bank credit linkage for rural women.',null,null,'https://nrlm.gov.in',18,null,'female','["all"]','["all"]',null,'["self_employed","homemaker","daily_wage"]',null,'rural',true,false,false,'Join or form an SHG in your village through Block Mission Management Unit.','["Aadhaar","Bank account","SHG formation documents"]'],
  ['senior-citizen-saving','Senior Citizens Savings Scheme','वरिष्ठ नागरिक बचत योजना','senior-citizen','central','Ministry of Finance','High-interest savings scheme for people above 60 years. Interest rate 8.2% per annum. Maximum deposit Rs 30 lakh. 5-year tenure extendable by 3 years. Tax benefit under Section 80C.','8.2% interest savings for senior citizens. Maximum deposit Rs 30 lakh.',30000000,null,'https://www.nsiindia.gov.in',60,null,'all','["all"]','["all"]',null,'["retired","all"]',null,'all',false,false,false,'Visit any post office or authorized bank with age proof and deposit amount.','["Aadhaar","Age proof","PAN","Bank account"]'],
  ['indira-gandhi-pension','Indira Gandhi National Old Age Pension','इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन','senior-citizen','central','Ministry of Rural Development','Rs 200 per month for BPL persons aged 60-79 years. Rs 500 per month for BPL persons aged 80+ years. States may add their own contribution on top.','Rs 200-500 per month pension for BPL senior citizens.',6000,null,null,60,null,'all','["all"]','["all"]',null,'["all"]',null,'all',true,false,false,'Apply through Block/District office or Panchayat. Listed in BPL database.','["Aadhaar","Age proof","BPL certificate","Bank account"]'],
  ['disability-pension','Indira Gandhi National Disability Pension','इंदिरा गांधी राष्ट्रीय विकलांगता पेंशन','disability','central','Ministry of Rural Development','Rs 300 per month for BPL persons with severe disability (80%+) aged 18-79. Rs 500 per month for aged 80+. Disability certificate required from competent medical authority.','Rs 300-500 per month for BPL persons with 80%+ disability.',6000,null,null,18,null,'all','["all"]','["all"]',null,'["all"]',null,'all',true,false,true,'Apply through Block/District Social Welfare office.','["Aadhaar","Disability certificate (80%+)","BPL certificate","Bank account"]'],
  ['widow-pension','Indira Gandhi National Widow Pension','इंदिरा गांधी राष्ट्रीय विधवा पेंशन','women','central','Ministry of Rural Development','Rs 300 per month for BPL widows aged 40-79 years. Rs 500 per month for aged 80+.','Rs 300-500 per month pension for BPL widows.',6000,null,null,40,null,'female','["all"]','["all"]',null,'["all"]',null,'all',true,false,false,'Apply through Block/District Social Welfare office.','["Aadhaar","Death certificate of spouse","BPL certificate","Bank account"]'],
  ['national-family-benefit','National Family Benefit Scheme','राष्ट्रीय परिवार लाभ योजना','social','central','Ministry of Rural Development','One-time grant of Rs 20,000 to BPL household on death of primary breadwinner. Applicable for deaths in the age group 18-59 years.','Rs 20,000 one-time grant on death of BPL family breadwinner.',20000,null,null,18,59,'all','["all"]','["all"]',null,'["all"]',null,'all',true,false,false,'Apply through Block/District Social Welfare office within 1 year of death.','["Aadhaar","Death certificate","BPL certificate","Bank account","FIR (if applicable)"]'],
  ['sugamya-bharat','Sugamya Bharat Abhiyan - Accessible India','सुगम्य भारत अभियान','disability','central','Ministry of Social Justice','Makes public spaces, transport, and ICT accessible for persons with disabilities. Covers retrofitting of government buildings, accessible websites, and sign language interpretation.','Accessible public buildings, transport, and digital services for disabled persons.',null,null,'https://accessibleindia.gov.in',null,null,'all','["all"]','["all"]',null,'["all"]',null,'all',false,false,true,'Benefits through government implementation. Report inaccessible buildings at accessibleindia.gov.in.','[]'],
  ['udid-disability-card','Unique Disability ID (UDID) Card','विशिष्ट विकलांगता पहचान पत्र','disability','central','Ministry of Social Justice','Universal ID card for persons with disabilities. Required for availing all disability-related government benefits. Links disability certificate with Aadhaar for easy verification.','Universal disability ID card for accessing all government disability benefits.',null,'https://www.swavlambancard.gov.in','https://www.swavlambancard.gov.in',null,null,'all','["all"]','["all"]',null,'["all"]',null,'all',false,false,true,'Apply at swavlambancard.gov.in or district hospital. Get disability assessment.','["Aadhaar","Disability certificate","Photo","Medical reports"]'],
];

async function seedSchemes(): Promise<void> {
  const conn = await mysql.createConnection({
    host: process.env.MYSQL_HOST || 'localhost',
    port: parseInt(process.env.MYSQL_PORT || '3306', 10),
    user: process.env.MYSQL_USER || 'root',
    password: process.env.MYSQL_PASSWORD || '',
    database: process.env.MYSQL_DATABASE || 'paisareality',
  });

  console.log('Connected to MySQL. Seeding schemes...');

  const allSchemes = [...SCHEMES, ...MORE_SCHEMES];
  let count = 0;

  for (const s of allSchemes) {
    try {
      await conn.execute(
        `INSERT INTO schemes (slug, name, name_hi, category, level, ministry, description, benefit_summary, benefit_amount_max, apply_url, official_url, min_age, max_age, gender, states, categories, max_income, occupations, education_min, area, bpl_required, minority_only, disability_only, how_to_apply, documents_required, meta_title, meta_description, source_url, last_verified, is_active)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURDATE(), TRUE)
         ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), benefit_summary=VALUES(benefit_summary), benefit_amount_max=VALUES(benefit_amount_max), last_verified=CURDATE()`,
        [s.slug, s.name, s.name_hi, s.category, s.level, s.ministry, s.description, s.benefit_summary, s.benefit_amount_max, s.apply_url, s.official_url, s.min_age, s.max_age, s.gender, s.states, s.categories, s.max_income, s.occupations, s.education_min, s.area, s.bpl_required, s.minority_only, s.disability_only, s.how_to_apply, s.documents_required, s.meta_title, s.meta_description, s.source_url]
      );
      count++;
      console.log(`  [${count}] ${s.name}`);
    } catch (error) {
      const msg = error instanceof Error ? error.message : 'Unknown';
      console.error(`  Error for ${s.name}: ${msg}`);
    }
  }

  // Insert batch schemes
  for (const b of BATCH_SCHEMES) {
    try {
      await conn.execute(
        `INSERT INTO schemes (slug, name, name_hi, category, level, ministry, description, benefit_summary, benefit_amount_max, apply_url, official_url, min_age, max_age, gender, states, categories, max_income, occupations, education_min, area, bpl_required, minority_only, disability_only, how_to_apply, documents_required, meta_title, meta_description, source_url, last_verified, is_active)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CONCAT(?, ' | Paisa Reality'), CONCAT('Check eligibility for ', ?, '. Benefits, documents, how to apply.'), 'https://myscheme.gov.in', CURDATE(), TRUE)
         ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), benefit_summary=VALUES(benefit_summary), last_verified=CURDATE()`,
        [...b, b[1], b[1]]
      );
      count++;
      console.log(`  [${count}] ${b[1]}`);
    } catch (error) {
      const msg = error instanceof Error ? error.message : 'Unknown';
      console.error(`  Error for ${b[1]}: ${msg}`);
    }
  }

  console.log(`\nDone. ${count} schemes seeded.`);
  await conn.end();
}

seedSchemes().catch((error) => {
  console.error('Seed failed:', error);
  process.exit(1);
});